//Title:          Deploy application  using  Green blue deployment approach 
//Version:        v1.0
//Description:    This jenkins file build the deploy the instances and attach it with scaling group and ELB  
// Stages configured 
// Deploy the Application -Attach the Instance with Autoscaling group and ELB using the Green blue deployment approach 

#!groovy

node {
  
  step([$class: 'WsCleanup'])

  stage "Checkout Git repo"
    checkout scm

  stage "Deploy AMI"
   sh returnStdout: false, script: "bash ./cdeployment.sh ${AMI_ID}"

}
